name: kreasi_nusantara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6

  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  get_cli: ^1.8.1
  material_design_icons_flutter: ^7.0.7296
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  flutter_svg_provider: ^1.0.7

  google_maps_flutter: ^2.6.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  get_storage: ^2.1.1
  money2: ^5.0.1
  dio: ^5.4.3+1

  http: ^1.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

